# Generated by Django 3.0.6 on 2020-06-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='c_pk',
            new_name='c_profile_pk',
        ),
    ]
