# Generated by Django 3.0.6 on 2020-06-16 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200616_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingcart', '0002_auto_20200616_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalOrder',
            new_name='Order',
        ),
    ]
