# Generated by Django 3.0.6 on 2020-06-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_auto_20200616_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='cart',
            new_name='order',
        ),
    ]
