# Generated by Django 3.0.6 on 2020-06-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200604_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
    ]
