# Generated by Django 3.0.6 on 2020-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200616_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default-user.jpg', upload_to='users/', verbose_name='foto de perfil'),
        ),
    ]
