# Generated by Django 3.0.6 on 2020-05-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200530_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='executive',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
    ]
