# Generated by Django 3.0.6 on 2020-05-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin',
        ),
    ]
