# Generated by Django 3.0.6 on 2020-06-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
    ]
