# Generated by Django 3.0.6 on 2020-06-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200602_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='market.Author', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Editorial', verbose_name='editorial'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='market.Genre', verbose_name='generos'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale',
            field=models.CharField(blank=True, choices=[('C', '5%'), ('D', '10%'), ('Q', '15%'), ('V', '20%')], max_length=1, null=True, verbose_name='oferta'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
    ]
