# Generated by Django 3.0.6 on 2020-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200602_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sale',
            field=models.CharField(blank=True, choices=[('C', '5%'), ('D', '10%'), ('Q', '15%'), ('V', '20%')], max_length=1, null=True, verbose_name='promoción'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
    ]
