# Generated by Django 3.0.6 on 2020-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200618_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='descuento')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
