# Generated by Django 3.0.6 on 2020-06-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sale',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Discount', verbose_name='promoción'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Editorial', verbose_name='editorial'),
        ),
    ]
