# Generated by Django 3.0.6 on 2020-06-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20200618_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['value']},
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='value',
        ),
    ]
