# Generated by Django 3.0.6 on 2020-06-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20200618_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Discount', verbose_name='descuento'),
        ),
    ]
