# Generated by Django 3.0.6 on 2020-06-20 20:32

from django.db import migrations, models
import market.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20200620_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[market.models.validators.StringWithoutSlashValidator], verbose_name='nombre'),
        ),
    ]
