# Generated by Django 3.0.6 on 2020-06-20 20:34

from django.db import migrations, models
import market.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20200620_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=255, validators=[market.models.validators.StringWithoutSlashValidator], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=255, validators=[market.models.validators.StringWithoutSlashValidator], verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[market.models.validators.StringWithoutSlashValidator], verbose_name='nombre'),
        ),
    ]
