# Generated by Django 3.0.6 on 2020-06-21 17:23

import django.core.validators
from django.db import migrations, models
import market.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20200620_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'descuento', 'verbose_name_plural': 'descuentos'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['name'], 'verbose_name': 'editorial', 'verbose_name_plural': 'editoriales'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'género', 'verbose_name_plural': 'géneros'},
        ),
        migrations.AlterField(
            model_name='book',
            name='sinopsis',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99), market.models.validators.DiscountValidator], verbose_name='valor'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
