# Generated by Django 3.0.6 on 2020-06-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20200621_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sinopsis',
            field=models.TextField(max_length=1500),
        ),
    ]
