# Generated by Django 3.0.6 on 2020-06-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_auto_20200621_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sinopsis',
            field=models.TextField(max_length=800),
        ),
    ]
